drop database if exists health2;

select 'Db dropped ' as 'Info';

-- to make default users
-- do it with UI. script does not work. IDENTIFIED by 't1' here t1 is the password, can change so its different from user name
-- change in program db res too S2nSmsWSDao/src/main/resources/appconfig.properties' and test property file

-- CREATE USER 't1'@'localhost' IDENTIFIED by 't1';GRANT ALL PRIVILEGES ON *.* TO 't1'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

-- CREATE USER 't1'@'%' IDENTIFIED by 't1';GRANT ALL PRIVILEGES ON *.* TO 't1'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;



-- CREATE USER 't2'@'localhost' IDENTIFIED by 't2';GRANT ALL PRIVILEGES ON *.* TO 't2'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

-- CREATE USER 't2'@'%' IDENTIFIED by 't2';GRANT ALL PRIVILEGES ON *.* TO 't2'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

